### PR TITLE
Fix get custom fields query bug

### PR DESCRIPTION
**Pull request by moon-brillar**

### CODE REVIEW

**Comment by moon-brillar** [comment]
[Fix get custom fields query bug](https://trello.com/c/qSTlPqVc/1490-fix-get-custom-fields-query-bug)

**Comment by moon-brillar** [comment]
[Fix get custom fields query bug](https://trello.com/c/qSTlPqVc/1490-fix-get-custom-fields-query-bug)

**Review by FishChen1202 — APPROVED** [review]
r+++++++++++++++++++++

**Review by ericHao22 — COMMENTED** [review]
r+, thanks!!

**Pull request merged**
